project:
  type: book
  output-dir: _book

book:
  title: "Econometrics Powered by AI"
  subtitle: "An Introduction Using Cloud-based Python Notebooks"
  author: "Carlos Mendez"
  date: "2026"
  search: true
  page-navigation: true
  chapters:
    - index.qmd
    - ../notebooks_colab/ch00_Preface.ipynb
    - part: "Statistical Foundations"
      chapters:
        - ../notebooks_colab/ch01_Analysis_of_Economics_Data.ipynb
        - ../notebooks_colab/ch02_Univariate_Data_Summary.ipynb
        - ../notebooks_colab/ch03_The_Sample_Mean.ipynb
        - ../notebooks_colab/ch04_Statistical_Inference_for_the_Mean.ipynb
    - part: "Bivariate Regression"
      chapters:
        - ../notebooks_colab/ch05_Bivariate_Data_Summary.ipynb
        - ../notebooks_colab/ch06_The_Least_Squares_Estimator.ipynb
        - ../notebooks_colab/ch07_Statistical_Inference_for_Bivariate_Regression.ipynb
        - ../notebooks_colab/ch08_Case_Studies_for_Bivariate_Regression.ipynb
        - ../notebooks_colab/ch09_Models_with_Natural_Logarithms.ipynb
    - part: "Multiple Regression"
      chapters:
        - ../notebooks_colab/ch10_Data_Summary_for_Multiple_Regression.ipynb
        - ../notebooks_colab/ch11_Statistical_Inference_for_Multiple_Regression.ipynb
        - ../notebooks_colab/ch12_Further_Topics_in_Multiple_Regression.ipynb
        - ../notebooks_colab/ch13_Case_Studies_for_Multiple_Regression.ipynb
    - part: "Advanced Topics"
      chapters:
        - ../notebooks_colab/ch14_Regression_with_Indicator_Variables.ipynb
        - ../notebooks_colab/ch15_Regression_with_Transformed_Variables.ipynb
        - ../notebooks_colab/ch16_Checking_the_Model_and_Data.ipynb
        - ../notebooks_colab/ch17_Panel_Data_Time_Series_Data_Causation.ipynb

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    code-fold: false
    code-tools: true
    css: custom.css
    include-before-body: google-translate.html
